<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CentrosSeeder extends Seeder
{
    public function run(): void
    {
        $centros = [
            //DISTRITO CENTRAL
['municipio_id' => 1, 'nombre' =>  'Blanca - Esc. Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'Aldea Cerro Grande - Esc. Pedro Nufio'],
['municipio_id' => 1, 'nombre' =>  'Aldea Suyapa - Ceb. Monseñor Jacobo Caceres'],
['municipio_id' => 1, 'nombre' =>  'Altos de Los Pinos - Ceb Jaime Romero'],
['municipio_id' => 1, 'nombre' =>  'Altos Del Milagro - Esc. Dolores Watson de Reina'],
['municipio_id' => 1, 'nombre' =>  'Bo. Abajo - Esc. Centro America'],
['municipio_id' => 1, 'nombre' =>  'Bo. Bella Vista - Esc. Francisco Martinez Maradiaga'],
['municipio_id' => 1, 'nombre' =>  'Bo. Buenos Aires - Ceb Republica de Panama'],
['municipio_id' => 1, 'nombre' =>  'Bo. Casamata - Jardin, Escuela E Instituto. Francisco G. Penzotti'],
['municipio_id' => 1, 'nombre' =>  'Bo. Centro de Comayaguela - Inst. Mixto Hibueras'],
['municipio_id' => 1, 'nombre' =>  'Bo. Concepcion - Ceb Urbana de Varones Lempira'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Bosque - Ceb 14 de Julio'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Bosque - Instalaciones Colprosumah'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Calvario - Ceb Jose Santos Guardiola'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Chile - Ceb. Manuel Bonilla'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Manchen - Esc. Agustin Alonzo'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Manchen - Inst. Tecnico Cultura Popular'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Picachito - Esc. Arturo Alvarez Calderon No. 2'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Reparto - Antiguo Local Inst. El Reparto'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Reparto - Esc. Republica de Chile'],
['municipio_id' => 1, 'nombre' =>  'Bo. El Rincon - Esc. Republica de Venezuela'],
['municipio_id' => 1, 'nombre' =>  'Bo. Guacerique - Esc. Republica Del Brasil'],
['municipio_id' => 1, 'nombre' =>  'Bo. Guamilito - Esc. Jose Simon Azcona Hoyo No.2'],
['municipio_id' => 1, 'nombre' =>  'Bo. Guanacaste - Esc. De Niñas Jose Cecilio Del Valle'],
['municipio_id' => 1, 'nombre' =>  'Bo. La Cabaña - Esc. Urbana Mixta Gral. Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'Bo. La Cuesta - Esc. Felipe Calix'],
['municipio_id' => 1, 'nombre' =>  'Bo. La Granja - Esc. Club de Leones No. 2'],
['municipio_id' => 1, 'nombre' =>  'Bo. La Soledad - Esc. Roberto Michelletti Bain'],
['municipio_id' => 1, 'nombre' =>  'Bo. Las Delicias - Ceb. Alvaro Contreras'],
['municipio_id' => 1, 'nombre' =>  'Bo. Lempira - Esc. De Ensayo Dionisio de Herrera'],
['municipio_id' => 1, 'nombre' =>  'Bo. Los Dolores - Inst. Gustavo Adolfo Alvarado'],
['municipio_id' => 1, 'nombre' =>  'Bo. Morazan - Esc. Ramon Rosa'],
['municipio_id' => 1, 'nombre' =>  'Bo. Perpetuo Socorro - Inst. Jesus Aguilar Paz'],
['municipio_id' => 1, 'nombre' =>  'Bo. Perpetuo Socorro - Inst. Tecnico Cultura Popular'],
['municipio_id' => 1, 'nombre' =>  'Bo. Pueblo Nuevo - Ceb. Republica de Costa Rica'],
['municipio_id' => 1, 'nombre' =>  'Bo. San Felipe - Oficinas Del Infop'],
['municipio_id' => 1, 'nombre' =>  'Bo. San Rafael - Inst. Cultura Nacional'],
['municipio_id' => 1, 'nombre' =>  'Carpintero - Esc. Mariana Folgar de Ramirez'],
['municipio_id' => 1, 'nombre' =>  'Casa Quemada - Esc. Antonia Carias'],
['municipio_id' => 1, 'nombre' =>  'Ciudad España - Centro Basico El Trebol'],
['municipio_id' => 1, 'nombre' =>  'Coa Abajo - Esc. Ramon Rosa'],
['municipio_id' => 1, 'nombre' =>  'Coa Arriba - Esc. Republica de Honduras'],
['municipio_id' => 1, 'nombre' =>  'Cofradia - Esc. Jose Manuel Zepeda'],
['municipio_id' => 1, 'nombre' =>  'Col. 14 de Enero - Esc. Edas Carrasco'],
['municipio_id' => 1, 'nombre' =>  'Col. Abraham Lincoln - Centro Basico Principe de Asturias'],
['municipio_id' => 1, 'nombre' =>  'Col. Alameda - Esc. Republica de Honduras'],
['municipio_id' => 1, 'nombre' =>  'Col. Aleman - Inst. Monterrey'],
['municipio_id' => 1, 'nombre' =>  'Col. Alemania No. 1 - Esc. Rotario Sur'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos de la Divanna - Jardin de Niños Monserrat'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos de Loarque - Esc. Cirilo Vindel'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos de Los Laureles - Esc. Antonio R. Reina'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos de San Francisco - Esc. Altos de San Francisco'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos de San Isidro - Centro Comunal'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos de Santa Rosa - Esc. Enciende Una Luz'],
['municipio_id' => 1, 'nombre' =>  'Col. Altos Del Paraiso - Esc. Republica de Honduras No. 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Arcieri - Ceb Abog. Ramon Calix Figueroa'],
['municipio_id' => 1, 'nombre' =>  'Col. Arturo Quezada - Esc. Arturo Quezada'],
['municipio_id' => 1, 'nombre' =>  'Col. Aurora No. 1 - Jardin Esc. E Inst. Jarimer'],
['municipio_id' => 1, 'nombre' =>  'Col. Australia - Esc. Dr. David Corea Sanchez'],
['municipio_id' => 1, 'nombre' =>  'Col. Ayestas - Jn, Esc E Inst. Shalom Jireh'],
['municipio_id' => 1, 'nombre' =>  'Col. Bella Oriente - Esc. De Aplicacion Republica Del Paraguay'],
['municipio_id' => 1, 'nombre' =>  'Col. Bolivar - Jardin de Niños 10 de Septiembre'],
['municipio_id' => 1, 'nombre' =>  'Col. Brisas de Olancho - Esc. Reinado de España'],
['municipio_id' => 1, 'nombre' =>  'Col. Brisas de Suyapa - Jardin de Niños Fania'],
['municipio_id' => 1, 'nombre' =>  'Col. Brisas Del Norte - Esc. Froylan Turcios Canelas'],
['municipio_id' => 1, 'nombre' =>  'Col. Brisas Del Rio O Cante - Esc. Republica Del Peru'],
['municipio_id' => 1, 'nombre' =>  'Col. Brisas Del Valle - Esc. San Miguel de Heredia'],
['municipio_id' => 1, 'nombre' =>  'Col. Buenas Nuevas - Esc. Daniel Casco'],
['municipio_id' => 1, 'nombre' =>  'Col. Campo Cielo Sector No. 2 - Ceb. Rafael Antonio Castillo Lizardo'],
['municipio_id' => 1, 'nombre' =>  'Col. Canaan - Esc. Enmanuel'],
['municipio_id' => 1, 'nombre' =>  'Col. Canada - Esc. Reynaldo Salinas Lopez'],
['municipio_id' => 1, 'nombre' =>  'Col. Cantarero Lopez - Esc. Nora Gunera de Melgar'],
['municipio_id' => 1, 'nombre' =>  'Col. Cataluña - Ceb. Altagracia Sanchez Melendez'],
['municipio_id' => 1, 'nombre' =>  'Col. Centroamerica Este - Ceb Centro America Este'],
['municipio_id' => 1, 'nombre' =>  'Col. Centroamerica Oeste - Ceb Las Americas'],
['municipio_id' => 1, 'nombre' =>  'Col. Centroamericana I - Esc. Centroamericana'],
['municipio_id' => 1, 'nombre' =>  'Col. Cerro Grande Zona No. 2 - Esc. Cerro Grande'],
['municipio_id' => 1, 'nombre' =>  'Col. Cerro Grande Zona No. 2 - Jardin de Niños Cerro Grande No. 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Cruz Roja - Ceb Meneca de Mencia'],
['municipio_id' => 1, 'nombre' =>  'Col. Diecinueve de Septiembre - Ceb 19 de Septiembre'],
['municipio_id' => 1, 'nombre' =>  'Col. Divina Providencia - Ceb. Cristo Del Picacho'],
['municipio_id' => 1, 'nombre' =>  'Col. El Carrizal - Esc. Dolores Bustillo'],
['municipio_id' => 1, 'nombre' =>  'Col. El Carrizal No. 1 - Inst. Tecnico Luis Bogran'],
['municipio_id' => 1, 'nombre' =>  'Col. El Carrizal No. 2 - Esc. Republica Federal de Alemania'],
['municipio_id' => 1, 'nombre' =>  'Col. El Hatillo - Esc. Mixta Sotero Barahona'],
['municipio_id' => 1, 'nombre' =>  'Col. El Hogar - Esc. Republica Del Japon'],
['municipio_id' => 1, 'nombre' =>  'Col. El Progreso No. 1 - Jn. Buena Ventura'],
['municipio_id' => 1, 'nombre' =>  'Col. El Quebrachito - Esc. Miguel de Cervantes'],
['municipio_id' => 1, 'nombre' =>  'Col. El Retiro - Esc. Amilcar Raudales'],
['municipio_id' => 1, 'nombre' =>  'Col. El Rosario - Esc. 15 de Septiembre'],
['municipio_id' => 1, 'nombre' =>  'Col. El Sitio - Esc. Juan Ramón Molina'],
['municipio_id' => 1, 'nombre' =>  'Col. El Sitio - Esc. Latinoamericana'],
['municipio_id' => 1, 'nombre' =>  'Col. El Zarzal O Bethania - Esc. Juan Guifarro Lopez No. 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Era No. 1 - Esc. Miguel Andonie Fernandez'],
['municipio_id' => 1, 'nombre' =>  'Col. Era No. 2 - Inst. Polivalente Juan Calvino'],
['municipio_id' => 1, 'nombre' =>  'Col. Estados Unidos - Esc. Inmaculada Concepcion'],
['municipio_id' => 1, 'nombre' =>  'Col. Faldas Del Pedregal - Esc. Accion Civica Militar'],
['municipio_id' => 1, 'nombre' =>  'Col. Fatima - Esc. Republica Federal de Alemania No. 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Flor Del Campo - Esc. Estado de Israel'],
['municipio_id' => 1, 'nombre' =>  'Col. Flor Del Campo - Inst. Tecnico Saul Zelaya Jimenez'],
['municipio_id' => 1, 'nombre' =>  'Col. Flor No. 1 - Esc. Tiburcio Carias Andino'],
['municipio_id' => 1, 'nombre' =>  'Col. Florencia Sur - U.n.a.h.'],
['municipio_id' => 1, 'nombre' =>  'Col. Flores de Oriente - Esc. Bessy Watson de Reina'],
['municipio_id' => 1, 'nombre' =>  'Col. Francisco Morazan - Esc. Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'Col. Fraternidad - Esc. La Fraternidad'],
['municipio_id' => 1, 'nombre' =>  'Col. Fuerzas Unidas - Esc. Fuerzas Unidas'],
['municipio_id' => 1, 'nombre' =>  'Col. Godoy - Iglesia Amor Viviente'],
['municipio_id' => 1, 'nombre' =>  'Col. Gracias a Dios - Esc. Nueva Gracias Adios'],
['municipio_id' => 1, 'nombre' =>  'Col. Granada - Esc. Henry Merrian Weddle'],
['municipio_id' => 1, 'nombre' =>  'Col. Guaymuras - Esc. Guaymuras'],
['municipio_id' => 1, 'nombre' =>  'Col. Hato de Enmedio Sector 1 - Jn y Esc. Guia Tecnica Jose Trinidad Reyes'],
['municipio_id' => 1, 'nombre' =>  'Col. Hato de Enmedio Sector 2 - Esc. Experimental de Niños Para la Musica'],
['municipio_id' => 1, 'nombre' =>  'Col. Hato de Enmedio Sector 4 - Esc. De Aplicacion Republica Oriental Del Uruguay'],
['municipio_id' => 1, 'nombre' =>  'Col. Hato de Enmedio Sector 5 - Conservatorio Nacional de Musica'],
['municipio_id' => 1, 'nombre' =>  'Col. Hato de Enmedio Sector 6 - Inst. Hector Pineda Ugarte'],
['municipio_id' => 1, 'nombre' =>  'Col. Hato de Enmedio Sector 9 - Esc. Lizandro Quezada Bardales'],
['municipio_id' => 1, 'nombre' =>  'Col. Henry Merriam - Ceb Club Rotario N° 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Honduras - Esc. Republica de China'],
['municipio_id' => 1, 'nombre' =>  'Col. Humuya - Cire'],
['municipio_id' => 1, 'nombre' =>  'Col. Independencia - Esc. Independencia'],
['municipio_id' => 1, 'nombre' =>  'Col. Inestroza - Esc. Arturo Alvarez Calderon'],
['municipio_id' => 1, 'nombre' =>  'Col. Israel Norte - Esc. Enma Romero de Callejas'],
['municipio_id' => 1, 'nombre' =>  'Col. Izaguirre - Esc. Oscar A. Flores'],
['municipio_id' => 1, 'nombre' =>  'Col. Jardines de Toncontin - Ceb Ramon Villeda Morales'],
['municipio_id' => 1, 'nombre' =>  'Col. Jose Angel Ulloa - Esc. Jose Angel Ulloa'],
['municipio_id' => 1, 'nombre' =>  'Col. Jose Arturo Duarte - Ceb Alejandro Alvarenga'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No 1 - Ceb. Dr Esteban Mendoza'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No. 1 - Regional de Capacitacion Sur'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No. 2 - Ceb Roberto Sosa'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No. 2 - Inst. Tecnico Honduras'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No. 4 - Esc. John F. Kennedy'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No. 4 - Inst. España Jesus Milla Selva'],
['municipio_id' => 1, 'nombre' =>  'Col. Kennedy Super M. No. 6 - Ceb Oswaldo Lopez Arellano'],
['municipio_id' => 1, 'nombre' =>  'Col. La Campaña - Inst. San Jose Del Carmen'],
['municipio_id' => 1, 'nombre' =>  'Col. La Esperanza - Esc. 4 de Junio'],
['municipio_id' => 1, 'nombre' =>  'Col. La Esperanza - Esc. E Inst. Santa Monica'],
['municipio_id' => 1, 'nombre' =>  'Col. La Felicidad - Esc. Republica de España'],
['municipio_id' => 1, 'nombre' =>  'Col. La Flor No. 2 - Ceb Republica de Chile N° 2'],
['municipio_id' => 1, 'nombre' =>  'Col. La Haya - Esc. Ramon Amaya Amador'],
['municipio_id' => 1, 'nombre' =>  'Col. La Joya - Esc. Jose Pineda Gomez'],
['municipio_id' => 1, 'nombre' =>  'Col. La Joya de Amarateca - Ceb. La Joya'],
['municipio_id' => 1, 'nombre' =>  'Col. La Laguna - Esc. Jose Raul Castro'],
['municipio_id' => 1, 'nombre' =>  'Col. La Peña - Cepb El Eden'],
['municipio_id' => 1, 'nombre' =>  'Col. La Peña - Esc. Oscar Castro Tejada'],
['municipio_id' => 1, 'nombre' =>  'Col. La Popular - Esc. Canada'],
['municipio_id' => 1, 'nombre' =>  'Col. La Pradera - Esc. Jose Angel Zuniga Huete'],
['municipio_id' => 1, 'nombre' =>  'Col. La Primavera - The New Genesis'],
['municipio_id' => 1, 'nombre' =>  'Col. La Reforma - Inst. San Pablo'],
['municipio_id' => 1, 'nombre' =>  'Col. La Rosa - Esc. Dr. Modesto Rodas Alvarado'],
['municipio_id' => 1, 'nombre' =>  'Col. La Sosa - Esc. Jose Maria Casco'],
['municipio_id' => 1, 'nombre' =>  'Col. La Travesia - Ceb. Ramon Montoya Cerrato'],
['municipio_id' => 1, 'nombre' =>  'Col. La Travesia - Inst. Carlos R. Flores'],
['municipio_id' => 1, 'nombre' =>  'Col. Lara - Nashville School'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Brisas - Esc. Toribio Bustillo'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Colinas - Ceb Vida Abundante'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Mercedes - Ceb Simon Bolivar'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Palmas - Esc. Jose Simon Azcona'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Pavas - Esc. Saul Zelaya Jimenez'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Torres - Esc. Prof. Arturo Alvarez Calderon'],
['municipio_id' => 1, 'nombre' =>  'Col. Las Vegas Del Country - Ceb Ramon Montoya Cerrato'],
['municipio_id' => 1, 'nombre' =>  'Col. Loarque Sur - Jardin de Niños Aguilar Paz'],
['municipio_id' => 1, 'nombre' =>  'Col. Lomas Cortijo - Centro Educativo Nueva Sociedad'],
['municipio_id' => 1, 'nombre' =>  'Col. Lomas Del Norte - Esc. Virginia Ruiz de Ramos'],
['municipio_id' => 1, 'nombre' =>  'Col. Los Calpules - Ceb Manuel Zelaya Rosales'],
['municipio_id' => 1, 'nombre' =>  'Col. Los Calpules - Cepb Jose Hector Pavon'],
['municipio_id' => 1, 'nombre' =>  'Col. Los Pinos - Ceb Herman Herrera'],
['municipio_id' => 1, 'nombre' =>  'Col. Los Pinos - Jardin Alduvin Diaz Bonilla'],
['municipio_id' => 1, 'nombre' =>  'Col. Los Robles - Esc. Mixta Los Robles'],
['municipio_id' => 1, 'nombre' =>  'Col. Luis Landa - Universidad Pedagogica Nacional'],
['municipio_id' => 1, 'nombre' =>  'Col. Marichal - Kinder Amigos de America'],
['municipio_id' => 1, 'nombre' =>  'Col. Mary Flakes de Flores - Esc. Mary Flakes de Flores'],
['municipio_id' => 1, 'nombre' =>  'Col. Mayangle - Esc. Privada Renacimiento'],
['municipio_id' => 1, 'nombre' =>  'Col. Mirador de Oriente - Ceb. Tim Hines'],
['municipio_id' => 1, 'nombre' =>  'Col. Mirador San Isidro - Esc. West Mont'],
['municipio_id' => 1, 'nombre' =>  'Col. Miraflores - Ceb Republica de Nicaragua'],
['municipio_id' => 1, 'nombre' =>  'Col. Miraflores Sur - Ceb El Reino de Los Paises Bajos'],
['municipio_id' => 1, 'nombre' =>  'Col. Miramonte - Facultad de Ciencias Medicas'],
['municipio_id' => 1, 'nombre' =>  'Col. Modesto Rodas Alvarado - Jardin de Niños Marcelino Pineda Lopez'],
['municipio_id' => 1, 'nombre' =>  'Col. Modesto Rodas Alvarado Ii - Esc. Fuerzas Armadas'],
['municipio_id' => 1, 'nombre' =>  'Col. Monseñor Fiallos - Ceb Monseñor Ernesto Fiallos'],
['municipio_id' => 1, 'nombre' =>  'Col. Montelimar - Inst. Alfonso G. Zelaya (ANEXO)'],
['municipio_id' => 1, 'nombre' =>  'Col. Monterrey - Esc. Alba Nora Gunera de Melgar'],
['municipio_id' => 1, 'nombre' =>  'Col. Montes de Bendicion - Ceb. Montes de Bendicion'],
['municipio_id' => 1, 'nombre' =>  'Col. Montes de Los Olivos - Esc. Montes de Los Olivos'],
['municipio_id' => 1, 'nombre' =>  'Col. Montes Sinai - Ceb Jorge J. Larach'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Danli - Esc. Bessie W. De Reina'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Era I Ii Iii Etapas - Esc. Oscar Andres Rodriguez'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva España - Esc. Nueva España'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Esperanza - Esc. Tomas A. Dolmo'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Jerusalen 2 - Esc. Nueva Jerusalen'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Providencia - Jardin de Niños Union y Esfuerzo'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Suyapa - Ceb 11 de Junio'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Suyapa - Esc. 17 de Septiembre'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Suyapa - Esc. Pablo Portillo Figueroa'],
['municipio_id' => 1, 'nombre' =>  'Col. Nueva Suyapa - Esc. Victor F. Ardon'],
['municipio_id' => 1, 'nombre' =>  'Col. Obrera - Jardin de Niños Paca Vda. De Lardizabal'],
['municipio_id' => 1, 'nombre' =>  'Col. Once de Junio - Suazo Cordova - Esc. Santa Margarita Bourgeoys'],
['municipio_id' => 1, 'nombre' =>  'Col. Oscar A. Flores - Esc. Republica de Italia'],
['municipio_id' => 1, 'nombre' =>  'Col. Palmira - Inst. Liceo Español'],
['municipio_id' => 1, 'nombre' =>  'Col. Payaqui - Inst. San Miguel San Juan Bosco'],
['municipio_id' => 1, 'nombre' =>  'Col. Pedregal de San Jose - Esc. Republica Del Peru'],
['municipio_id' => 1, 'nombre' =>  'Col. Plan de Los Pinos - Ceb Melida Jesus Muñoz'],
['municipio_id' => 1, 'nombre' =>  'Col. Policarpo Paz Garcia - Esc. Policarpo Paz Garcia'],
['municipio_id' => 1, 'nombre' =>  'Col. Primero de Diciembre - Instituto Mexico'],
['municipio_id' => 1, 'nombre' =>  'Col. Quince de Septiembre - Colegio de Abogados'],
['municipio_id' => 1, 'nombre' =>  'Col. Rafael Callejas - Ceb Marco Tulio Cruz'],
['municipio_id' => 1, 'nombre' =>  'Col. Ramon Amaya Amador - Esc. Ronaldo Roll'],
['municipio_id' => 1, 'nombre' =>  'Col. Republica de Venezuela - Esc. Raul Zaldivar'],
['municipio_id' => 1, 'nombre' =>  'Col. Res. La Cañada - Esc. Jose Ramon Calix Figueroa'],
['municipio_id' => 1, 'nombre' =>  'Col. Reynel Funez - Ceb Republica de Honduras'],
['municipio_id' => 1, 'nombre' =>  'Col. Rio Grande Sur - Inice'],
['municipio_id' => 1, 'nombre' =>  'Col. Rodriguez - Esc. Centroamericana'],
['municipio_id' => 1, 'nombre' =>  'Col. Rosalinda - Ceb. Carlos Roberto Reina'],
['municipio_id' => 1, 'nombre' =>  'Col. Ruben Dario - Asociacion Nacional de Scouts de Honduras'],
['municipio_id' => 1, 'nombre' =>  'Col. Ruben Dario - Cenaculo School'],
['municipio_id' => 1, 'nombre' =>  'Col. Sabana Grande - Oficinas Del Pani'],
['municipio_id' => 1, 'nombre' =>  'Col. Sagastume - Ceb. Maximiliano Sagastume'],
['municipio_id' => 1, 'nombre' =>  'Col. San Angel - Esc. Nacional de Arte Dramático'],
['municipio_id' => 1, 'nombre' =>  'Col. San Angel - Oficinas Del Infop'],
['municipio_id' => 1, 'nombre' =>  'Col. San Francisco - Esc. Jesus Aguilar Paz'],
['municipio_id' => 1, 'nombre' =>  'Col. San Francisco - Esc. Republica de Francia'],
['municipio_id' => 1, 'nombre' =>  'Col. San Francisco - Inst. Superacion San Francisco'],
['municipio_id' => 1, 'nombre' =>  'Col. San Jose de la Peña - Esc. Paquita Guerrero Viuda de Lardizabal'],
['municipio_id' => 1, 'nombre' =>  'Col. San Jose de la Vega - Esc. Michell J. Hasbum'],
['municipio_id' => 1, 'nombre' =>  'Col. San Juan Bosco - Esc. Carlos Roberto Reina'],
['municipio_id' => 1, 'nombre' =>  'Col. San Juan Del Norte No. 2 - Esc. San Juan Del Norte'],
['municipio_id' => 1, 'nombre' =>  'Col. San Luis - Esc. Camara Junior'],
['municipio_id' => 1, 'nombre' =>  'Col. San Martin - Esc. Jose de San Martin'],
['municipio_id' => 1, 'nombre' =>  'Col. San Miguel - Esc. Juan Ramon Molina'],
['municipio_id' => 1, 'nombre' =>  'Col. San Miguel - Jardin Rafael Pineda Ponce'],
['municipio_id' => 1, 'nombre' =>  'Col. San Miguel Arcangel - Ceb San Miguel Arcangel'],
['municipio_id' => 1, 'nombre' =>  'Col. Santa Cecilia - Esc. Eusebio Ventura'],
['municipio_id' => 1, 'nombre' =>  'Col. Santa Eduviges - Esc. Alfonso Guillen Zelaya'],
['municipio_id' => 1, 'nombre' =>  'Col. Santa Isabel - Esc. San Jeronimo Emiliani'],
['municipio_id' => 1, 'nombre' =>  'Col. Santa Maria - Esc. Latinoamericana'],
['municipio_id' => 1, 'nombre' =>  'Col. Satelite - Esc. Itzamna'],
['municipio_id' => 1, 'nombre' =>  'Col. Satelite - Inst. Cultura Nacional Sur'],
['municipio_id' => 1, 'nombre' =>  'Col. Smith No. 2 - Esc. Rafael Leonardo Callejas'],
['municipio_id' => 1, 'nombre' =>  'Col. Soto - Esc. Leovigildo Pineda Cardona'],
['municipio_id' => 1, 'nombre' =>  'Col. Tepeyac - Oficina Central Del I.n.a.'],
['municipio_id' => 1, 'nombre' =>  'Col. Tiloarque No. 1 - Inst. Central Vicente Caceres'],
['municipio_id' => 1, 'nombre' =>  'Col. Torocagua - Ceb Republica de Guatemala'],
['municipio_id' => 1, 'nombre' =>  'Col. Treinta de Noviembre - Centro Comunal'],
['municipio_id' => 1, 'nombre' =>  'Col. Treinta de Noviembre - Esc. Republica de España'],
['municipio_id' => 1, 'nombre' =>  'Col. Tres de Mayo - Esc. Rafael Pineda Ponce'],
['municipio_id' => 1, 'nombre' =>  'Col. Unidad y Fuerza - Ceb Rafael Pineda Ponce # 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Veintiuno de Febrero - Esc. Roberto Suazo Cordova'],
['municipio_id' => 1, 'nombre' =>  'Col. Veintiuno de Octubre - Esc. 21 de Octubre'],
['municipio_id' => 1, 'nombre' =>  'Col. Victor F. Ardon - Esc. Hefzi-Ba'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Cristina - Esc. 20 de Julio'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Franca - Ceb. Desarrollo Juvenil'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Linda Miller - Esc. Ricardo Ernesto Maduro Andrews'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Los Laureles - Ceb Luis Pasteur'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Nueva Suyapa - Inst. Nueva Suyapa'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Nueva Suyapa - Jn. Lourdes de Monserrat'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Suyapa - Esc. Villa Olimpica'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Union - Esc. Nuevos Horizontes No.1'],
['municipio_id' => 1, 'nombre' =>  'Col. Villa Universitaria - Complejo Simon Azcona'],
['municipio_id' => 1, 'nombre' =>  'Col. Villanueva Norte - Inst. Rafael Pineda Ponce'],
['municipio_id' => 1, 'nombre' =>  'Col. Villanueva Norte Sector 1 - Esc. Dr. Jorge Roberto Maradiaga'],
['municipio_id' => 1, 'nombre' =>  'Col. Villanueva Sector 2 - Esc. Evangelica Piedad No. 2'],
['municipio_id' => 1, 'nombre' =>  'Col. Villanueva Sur Sector 3 - Esc. Doctor David Corea Sanchez'],
['municipio_id' => 1, 'nombre' =>  'Col. Villanueva Sur Sector 4 - Ceb Naciones Unidas'],
['municipio_id' => 1, 'nombre' =>  'Col. Villanueva Sur Sector 5 - Ceb Gustavo Simon Nuñez'],
['municipio_id' => 1, 'nombre' =>  'Col. Villeda Morales - Ceb. Manuel Bonilla'],
['municipio_id' => 1, 'nombre' =>  'Col. Zapote Centro - Esc. Ibrahim Gamero'],
['municipio_id' => 1, 'nombre' =>  'Concepcion de Rio Grande O Nueva Concep. - Esc. Dionisio de Herrera'],
['municipio_id' => 1, 'nombre' =>  'El Aguacate - Ceb Manuel Bonilla'],
['municipio_id' => 1, 'nombre' =>  'El Durazno - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 1, 'nombre' =>  'El Empedrado - Esc. Norberto Guillen'],
['municipio_id' => 1, 'nombre' =>  'El Guanabano - Esc. Julian Lopez Pineda'],
['municipio_id' => 1, 'nombre' =>  'El Guayabo - Esc. Maria E. De Inestroza'],
['municipio_id' => 1, 'nombre' =>  'El Jicarito - Esc. Independencia'],
['municipio_id' => 1, 'nombre' =>  'El Lolo - Esc. Crescencio Rodriguez'],
['municipio_id' => 1, 'nombre' =>  'El Naranjal - Ceb. Republica de Guatemala'],
['municipio_id' => 1, 'nombre' =>  'El Piliguin - Esc. Rural Mixta Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'El Reventon - Esc. Luis Landa'],
['municipio_id' => 1, 'nombre' =>  'El Tablon - Ceb Nemesia Portillo'],
['municipio_id' => 1, 'nombre' =>  'El Terrero - Esc. Dionisio de Herrera'],
['municipio_id' => 1, 'nombre' =>  'El Tizatillo - Ceb Leon Alvarado'],
['municipio_id' => 1, 'nombre' =>  'Germania - Esc. Ruben Martinez Rodas'],
['municipio_id' => 1, 'nombre' =>  'Guangololo - Esc. Cristobal Colon'],
['municipio_id' => 1, 'nombre' =>  'Guasculile - Esc. Marco Aurelio Soto'],
['municipio_id' => 1, 'nombre' =>  'La Calera - Esc. Luis Landa'],
['municipio_id' => 1, 'nombre' =>  'La Calera - Esc. Petrona Lagos'],
['municipio_id' => 1, 'nombre' =>  'La Cañada - Ceb Nicolas Urquieta'],
['municipio_id' => 1, 'nombre' =>  'La Cañada - Esc. Lisandro Sagastume'],
['municipio_id' => 1, 'nombre' =>  'La Cieneguita - Esc. Marina de Maradiaga'],
['municipio_id' => 1, 'nombre' =>  'La Cuesta No. 2 - Esc. Bonifacio Reyes'],
['municipio_id' => 1, 'nombre' =>  'La Jagua - Esc. 21 de Octubre'],
['municipio_id' => 1, 'nombre' =>  'La Laguna - Esc. Luis Landa'],
['municipio_id' => 1, 'nombre' =>  'La Puerta - Esc. Henry Merriam'],
['municipio_id' => 1, 'nombre' =>  'La Sabana - Esc. Ruben Barahona'],
['municipio_id' => 1, 'nombre' =>  'La Venta - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 1, 'nombre' =>  'Las Casitas - Ceb. Jose Cecilio Del Valle'],
['municipio_id' => 1, 'nombre' =>  'Las Flores - Ceb Augusto C. Coello'],
['municipio_id' => 1, 'nombre' =>  'Las Moras - Esc. Dolores Reina de Watson'],
['municipio_id' => 1, 'nombre' =>  'Las Nuevas Flores - Esc. Eugenio Matute Canizales'],
['municipio_id' => 1, 'nombre' =>  'Las Oricas - Esc. Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'Las Pilas - Esc. Republica de Honduras'],
['municipio_id' => 1, 'nombre' =>  'Las Tapias - Esc. Miguel Morazan'],
['municipio_id' => 1, 'nombre' =>  'Los Jutes - Esc. Sergio Palacios'],
['municipio_id' => 1, 'nombre' =>  'Los Planes - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 1, 'nombre' =>  'Mateo - Esc. Romulo E. Duron'],
['municipio_id' => 1, 'nombre' =>  'Monte Redondo - Ceb Jose Cecilio Del Valle'],
['municipio_id' => 1, 'nombre' =>  'Monte Redondo - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 1, 'nombre' =>  'Nueva Aldea - Esc. Vicente Caceres'],
['municipio_id' => 1, 'nombre' =>  'Nueva Capital - Esc. Y Inst. Santa Teresa de Jesus'],
['municipio_id' => 1, 'nombre' =>  'Nueva Venta - Esc. Marco Aurelio Soto'],
['municipio_id' => 1, 'nombre' =>  'Rio Abajo - Esc. Pedro Nufio'],
['municipio_id' => 1, 'nombre' =>  'Rio Hondo - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 1, 'nombre' =>  'San Francisco de Soroguara - Esc. Manuel Bonilla'],
['municipio_id' => 1, 'nombre' =>  'San Jose de Soroguara - Ceb Dionisio de Herrera'],
['municipio_id' => 1, 'nombre' =>  'San Jose Del Potrero - Esc. Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'San Juan Del Rancho - Ceb Francisco Morazan'],
['municipio_id' => 1, 'nombre' =>  'San Juan Del Rio Grande - Esc. Esteban Guardiola'],
['municipio_id' => 1, 'nombre' =>  'San Juancito - Esc. Marco Aurelio Soto'],
['municipio_id' => 1, 'nombre' =>  'San Matias No. 2 - Ceb Vicente Caceres'],
['municipio_id' => 1, 'nombre' =>  'Santa Cruz Abajo - Esc. Luis A. Escalante'],
['municipio_id' => 1, 'nombre' =>  'Santa Cruz Arriba - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 1, 'nombre' =>  'Santa Elena - Esc. Victor Manuel Lozano'],
['municipio_id' => 1, 'nombre' =>  'Santa Rosa - Ceb 3 de Octubre'],
['municipio_id' => 1, 'nombre' =>  'Suntule - Esc. Dr. Salvador Corleto'],
['municipio_id' => 1, 'nombre' =>  'Tamara - Esc. Juan Lindo'],
['municipio_id' => 1, 'nombre' =>  'Villa Real - Esc. Mauricio Bonilla A.'],
['municipio_id' => 1, 'nombre' =>  'Villa Vieja - Ceb Policarpo Bonilla'],
['municipio_id' => 1, 'nombre' =>  'Yaguacire - Esc. La Fraternidad'],
['municipio_id' => 1, 'nombre' =>  'Zambrano - Esc'],

//ALUBAREN
['municipio_id' => 2, 'nombre' =>  'Alubaren - Ceb Ramon Rosa'],
['municipio_id' => 2, 'nombre' =>  'Centro Del Valle O la Concepcion - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 2, 'nombre' =>  'El Divisadero - Esc. Francisco Morazan'],
['municipio_id' => 2, 'nombre' =>  'El Hatillo - Esc. Juan Manuel Galvez'],
['municipio_id' => 2, 'nombre' =>  'El Jicaro - Esc. Proheco'],
['municipio_id' => 2, 'nombre' =>  'Los Tablones - Instituto Oscar Arnulfo Fiallos'],
['municipio_id' => 2, 'nombre' =>  'San Antonio - Esc. Francisco Morazan'],
['municipio_id' => 2, 'nombre' =>  'Santa Rita - Esc.'],

//CEDROS
['municipio_id' => 3, 'nombre' =>  'Agalteca - Esc. Carmen de Carias'],
['municipio_id' => 3, 'nombre' =>  'Agua Blanca - Esc. Jaime Romero Zuniga'],
['municipio_id' => 3, 'nombre' =>  'Cedros - Esc. Alvaro Contreras'],
['municipio_id' => 3, 'nombre' =>  'El Aguacatal - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 3, 'nombre' =>  'El Empalme - Esc. 17 de Junio'],
['municipio_id' => 3, 'nombre' =>  'El Guante - Ceb Miguel Paz Barahona'],
['municipio_id' => 3, 'nombre' =>  'El Suyatal - Esc. Esteban Guardiola'],
['municipio_id' => 3, 'nombre' =>  'El Tablon - Ceb Juan Lindo'],
['municipio_id' => 3, 'nombre' =>  'La Guadalupe - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 3, 'nombre' =>  'Las Animas - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 3, 'nombre' =>  'Las Crucitas - Esc. Raul Zaldivar'],
['municipio_id' => 3, 'nombre' =>  'Las Lajitas - Esc. Francisco Morazan'],
['municipio_id' => 3, 'nombre' =>  'Los Portillos - Esc. Rural Mixta Ramon Rosa'],
['municipio_id' => 3, 'nombre' =>  'Los Trozos - Esc. Jose Trinidad Reyes'],
['municipio_id' => 3, 'nombre' =>  'Mata de Platano - Ceb Manuel Bonilla'],
['municipio_id' => 3, 'nombre' =>  'Pueblo Nuevo - Ceb Francisco Morazán'],
['municipio_id' => 3, 'nombre' =>  'Siria - Esc. Pedro Nufio'],
['municipio_id' => 3, 'nombre' =>  'Tamarindo - Es'],

//CURAREN
['municipio_id' => 4, 'nombre' =>  'Cacagua - Esc. Ramon Ortega'],
['municipio_id' => 4, 'nombre' =>  'Cunimisca - Ceb Francisco Cardona'],
['municipio_id' => 4, 'nombre' =>  'Curaren - Esc. Ramon Rosa'],
['municipio_id' => 4, 'nombre' =>  'El Anis - Esc. Alvaro Contreras'],
['municipio_id' => 4, 'nombre' =>  'El Arado - Esc. Pedro Nufio'],
['municipio_id' => 4, 'nombre' =>  'El Chaparral - Esc. Dionisio de Herrera'],
['municipio_id' => 4, 'nombre' =>  'El Escalon - Esc. Juan Manuel Galvez'],
['municipio_id' => 4, 'nombre' =>  'El Portillo de San Juan Bosco - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 4, 'nombre' =>  'El Porvenir - Esc. Francisco Morazan'],
['municipio_id' => 4, 'nombre' =>  'El Tamboral - Esc. Rural Mixta Alvaro Contreras'],
['municipio_id' => 4, 'nombre' =>  'Emituca - Esc. Jose Trinidad Reyes'],
['municipio_id' => 4, 'nombre' =>  'Jardines - Ceb Francisco Morazan'],
['municipio_id' => 4, 'nombre' =>  'La Costita - Esc. Juan Manuel Galvez'],
['municipio_id' => 4, 'nombre' =>  'La Laguna - Esc. Francisco Morazan'],
['municipio_id' => 4, 'nombre' =>  'La Victorina - Esc. Lempira'],
['municipio_id' => 4, 'nombre' =>  'Las Mesitas - Ceb Marco Aurelio Soto'],
['municipio_id' => 4, 'nombre' =>  'Lodo Negro - Ceb Jose Trinidad Reyes'],
['municipio_id' => 4, 'nombre' =>  'Los Arenales - Esc. John F. Kennedy'],
['municipio_id' => 4, 'nombre' =>  'Malagua - Esc. Juan Lindo'],
['municipio_id' => 4, 'nombre' =>  'Malicre - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 4, 'nombre' =>  'Mandasta - Esc. Luis Landa'],
['municipio_id' => 4, 'nombre' =>  'San Isidro - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 4, 'nombre' =>  'San Marcos - Ceb Jose Cecilio Del Valle'],
['municipio_id' => 4, 'nombre' =>  'San Roman - Esc. Jose Trinidad Reyes'],
['municipio_id' => 4, 'nombre' =>  'Tapope - Esc. Manuel Bonilla'],
['municipio_id' => 4, 'nombre' =>  'Tinorio - Esc. Alfonso Guillen Zelaya'],
['municipio_id' => 4, 'nombre' =>  'Toncontin - Esc. R'],

//EL PORVENIR
['municipio_id' => 5, 'nombre' =>  'El Agua Caliente - Ceb Alvaro Contreras'],
['municipio_id' => 5, 'nombre' =>  'El Escanito - Esc. 15 de Septiembre'],
['municipio_id' => 5, 'nombre' =>  'El Guantillo - Ceb Union Lempira'],
['municipio_id' => 5, 'nombre' =>  'El Palmar - Esc. Francisco Morazan'],
['municipio_id' => 5, 'nombre' =>  'El Pedernal - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 5, 'nombre' =>  'El Porvenir - Ceb Jose Trinidad Reyes'],
['municipio_id' => 5, 'nombre' =>  'El Terrero - Ceb Marco Aurelio Soto'],
['municipio_id' => 5, 'nombre' =>  'Guayabillas - Esc. Republica de Argentina'],
['municipio_id' => 5, 'nombre' =>  'Los Horcones - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 5, 'nombre' =>  'Pueblo Nuevo - '],

//GUAIMACA
['municipio_id' => 6, 'nombre' =>  'Bo. Arriba - Ceb Republica de Mexico'],
['municipio_id' => 6, 'nombre' =>  'Bo. El Centro - Inst. Jose de la Rosa'],
['municipio_id' => 6, 'nombre' =>  'Bo. Suyapa - Jardin de Niños Emma Romero de Callejas'],
['municipio_id' => 6, 'nombre' =>  'Cerro Bonito - Ceb la Luz'],
['municipio_id' => 6, 'nombre' =>  'Col. Alemania - Esc. Rene Bendaña'],
['municipio_id' => 6, 'nombre' =>  'Col. San Juan - Ceb Dr. David Corea Sanchez'],
['municipio_id' => 6, 'nombre' =>  'Col. Veintiuno de Noviembre - Ceb 21 de Noviembre'],
['municipio_id' => 6, 'nombre' =>  'El Caulote - Esc. Roberto Fernandez'],
['municipio_id' => 6, 'nombre' =>  'El Chelon No. 1 - Esc. Republica de Guatemala'],
['municipio_id' => 6, 'nombre' =>  'El Destino - Esc. Republica de Italia'],
['municipio_id' => 6, 'nombre' =>  'El Guaracacal - Ceb 5 de Septiembre'],
['municipio_id' => 6, 'nombre' =>  'El Tomate - Esc. 14 de Abril'],
['municipio_id' => 6, 'nombre' =>  'Gones - Esc. José Cecilio Del Valle'],
['municipio_id' => 6, 'nombre' =>  'La Aserradera - Esc. Cristobal Colon'],
['municipio_id' => 6, 'nombre' =>  'La Laguna - Esc. 12 de Abril'],
['municipio_id' => 6, 'nombre' =>  'La Nava - Esc. Luis Andres Zuniga'],
['municipio_id' => 6, 'nombre' =>  'La Tumba - Esc. Republica de Costa Rica'],
['municipio_id' => 6, 'nombre' =>  'Los Jobos - Esc. Republica de Honduras'],
['municipio_id' => 6, 'nombre' =>  'Majastre - Esc. Rolando Rodriguez'],
['municipio_id' => 6, 'nombre' =>  'Maraquito - Esc. Republica de Honduras'],
['municipio_id' => 6, 'nombre' =>  'Nueva Esmeralda O la Esmeralda - Esc. Nueva Esmeralda'],
['municipio_id' => 6, 'nombre' =>  'Rio Abajo - Esc. Marcos Carias Reyes'],
['municipio_id' => 6, 'nombre' =>  'Sabanagrande O Puente Jalan - Ceb Lempira'],
['municipio_id' => 6, 'nombre' =>  'San Jose - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 6, 'nombre' =>  'San Marcos - Ceb Presentacion Centeno'],
['municipio_id' => 6, 'nombre' =>  'Sanquin - Esc. M'],

//LA LIBERTAD
['municipio_id' => 7, 'nombre' =>  'Cerro Colorado - Esc. Jose Trinidad Reyes'],
['municipio_id' => 7, 'nombre' =>  'El Jicarillo - Esc. Dionisio de Herrera'],
['municipio_id' => 7, 'nombre' =>  'La Libertad - Esc. Moises Aguilar'],
['municipio_id' => 7, 'nombre' =>  'Quebrachal - Esc. V'],

//LA VENTA
['municipio_id' => 8, 'nombre' =>  'El Algodonal - Esc. Raul Zaldivar'],
['municipio_id' => 8, 'nombre' =>  'El Bombon - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 8, 'nombre' =>  'El Carrizal - Esc. 1 de Mayo'],
['municipio_id' => 8, 'nombre' =>  'El Espino - Esc. Inmaculada Concepcion'],
['municipio_id' => 8, 'nombre' =>  'El Llano - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 8, 'nombre' =>  'El Tablon - Esc. Juan Lindo'],
['municipio_id' => 8, 'nombre' =>  'Guilupe O San Jorge - Esc. Dionisio de Herrera'],
['municipio_id' => 8, 'nombre' =>  'La Cañada - Esc. Lempira'],
['municipio_id' => 8, 'nombre' =>  'La Ramada - Esc. Juan de la Cruz Ordoñez'],
['municipio_id' => 8, 'nombre' =>  'La Tejera - Esc. Ramon Rosa'],
['municipio_id' => 8, 'nombre' =>  'La Venta - Ceb Gilda Lagos'],
['municipio_id' => 8, 'nombre' =>  'Las Delicias - Esc. Jose Santos Guardiola'],
['municipio_id' => 8, 'nombre' =>  'Las Marias - Esc. Oscar Ramon Zelaya'],
['municipio_id' => 8, 'nombre' =>  'Ojos de Agua - Es'],

//LEPATERIQUE
['municipio_id' => 9, 'nombre' =>  'Apostol Santiago - Esc. Ramon Rosa'],
['municipio_id' => 9, 'nombre' =>  'Cerro Verde O Trinidad - Ceb la Trinidad'],
['municipio_id' => 9, 'nombre' =>  'Culguaque - Ceb Rafael Almendarez'],
['municipio_id' => 9, 'nombre' =>  'El Aguacate - Ceb Marco Aurelio Soto'],
['municipio_id' => 9, 'nombre' =>  'El Carrizal U Oropule - Ceb José Cecilio Del Valle'],
['municipio_id' => 9, 'nombre' =>  'El Escarbadero - Esc. Santa Isabel'],
['municipio_id' => 9, 'nombre' =>  'El Guayabo - Esc. Juan Ramon Molina'],
['municipio_id' => 9, 'nombre' =>  'El Hatillo - Esc. 15 de Septiembre'],
['municipio_id' => 9, 'nombre' =>  'El Naranjo - Ceb. Francisco Morazan'],
['municipio_id' => 9, 'nombre' =>  'El Ovejo - Esc. Republica de Honduras'],
['municipio_id' => 9, 'nombre' =>  'El Rodeo - Esc. Maria Trinidad Martinez'],
['municipio_id' => 9, 'nombre' =>  'El Suyatillo - Esc. Juan Lindo'],
['municipio_id' => 9, 'nombre' =>  'La Brea - Esc. Pompilio Ortega'],
['municipio_id' => 9, 'nombre' =>  'La Estancia - Ceb Cristobal Colón'],
['municipio_id' => 9, 'nombre' =>  'Las Gradas - Esc. Republica de Honduras'],
['municipio_id' => 9, 'nombre' =>  'Las Tablas - Esc. Froylan Turcios'],
['municipio_id' => 9, 'nombre' =>  'Lepaterique - Esc. Manuel Bonilla'],
['municipio_id' => 9, 'nombre' =>  'Lepateriquillo - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 9, 'nombre' =>  'Llano Del Conejo - Esc. Francisco Morazan'],
['municipio_id' => 9, 'nombre' =>  'Mulhuaca O El Llano - Ceb Augusto C Coello'],
['municipio_id' => 9, 'nombre' =>  'Ocote Hueco - Ceb José Trinidad Reyes'],
['municipio_id' => 9, 'nombre' =>  'Palo Marcado - Esc. Augusto C. Coello'],
['municipio_id' => 9, 'nombre' =>  'Piedra Rayada - Esc. Lempira'],
['municipio_id' => 9, 'nombre' =>  'Planes de Cipres - Esc. Juan Pablo Ii'],
['municipio_id' => 9, 'nombre' =>  'Quebrada Honda - Esc. Elias Avila'],
['municipio_id' => 9, 'nombre' =>  'Regadillos - Esc. Froylan Turcios'],
['municipio_id' => 9, 'nombre' =>  'Sabana Redonda - Esc. Vicente Martinez'],
['municipio_id' => 9, 'nombre' =>  'Tierra Colorada - Esc. Ramon Villeda Morales'],
['municipio_id' => 9, 'nombre' =>  'Turturupe - Esc. Francisco Morazan'],
['municipio_id' => 9, 'nombre' =>  'Ulasala - Esc. Celestina Servellon'],
['municipio_id' => 9, 'nombre' =>  'Vallecillos - Ceb '],

//MARAITA
['municipio_id' => 10, 'nombre' =>  'Coato - Esc. Juan Ramon Molina'],
['municipio_id' => 10, 'nombre' =>  'El Chaguite - Esc. Miguel Morazan'],
['municipio_id' => 10, 'nombre' =>  'El Quiquisque - Esc. Lempira'],
['municipio_id' => 10, 'nombre' =>  'El Retiro - Esc. Pedro C. Quiñonez'],
['municipio_id' => 10, 'nombre' =>  'Las Agujas - Esc. Jose Trinidad Reyes'],
['municipio_id' => 10, 'nombre' =>  'Las Tablas - Esc. Luis Landa'],
['municipio_id' => 10, 'nombre' =>  'Maraita - Esc. Miguel Paz Barahona'],
['municipio_id' => 10, 'nombre' =>  'Terreritos - Esc. Martha Nazar'],
['municipio_id' => 10, 'nombre' =>  'Terrero Blanco - Esc. Francisco Morazan'],
['municipio_id' => 10, 'nombre' =>  'Terrero de San Pedro - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 10, 'nombre' =>  'Terrero Prieto - E'],

//
['municipio_id' => 11, 'nombre' =>  'El Carrizal - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 11, 'nombre' =>  'El Derrumbe - Esc. Francisco Morazan'],
['municipio_id' => 11, 'nombre' =>  'El Panal - Esc. Roberto Suazo Cordova'],
['municipio_id' => 11, 'nombre' =>  'La Esperanza O El Cacao - Ceb Jose Rodriguez'],
['municipio_id' => 11, 'nombre' =>  'La Union - Escuela Dionisio de Herrera'],
['municipio_id' => 11, 'nombre' =>  'La Vega - Esc. Pedro Pascual Amaya'],
['municipio_id' => 11, 'nombre' =>  'Las Lagunas - Esc. Manuel de Jesus Subirana'],
['municipio_id' => 11, 'nombre' =>  'Los Planes - Esc. Juan Vicente Villalobos'],
['municipio_id' => 11, 'nombre' =>  'Marale - Esc. Landa Reyes'],
['municipio_id' => 11, 'nombre' =>  'Ojo de Agua - Esc. Alvaro Contreras'],
['municipio_id' => 11, 'nombre' =>  'Siale - Esc. Francisco Morazan'],
['municipio_id' => 11, 'nombre' =>  'Vallecito Arriba -'],

['municipio_id' => 12, 'nombre' =>  'Adurasta - Esc. Ramon Rosa'],
['municipio_id' => 12, 'nombre' =>  'Barajana - Esc. Marco Aurelio Soto'],
['municipio_id' => 12, 'nombre' =>  'El Junquillo - Esc. Rivaldo Oyuela'],
['municipio_id' => 12, 'nombre' =>  'Los Algodones - Esc. Republica de Honduras'],
['municipio_id' => 12, 'nombre' =>  'Nueva Armenia - Esc. Miguel Morazan'],
['municipio_id' => 12, 'nombre' =>  'Sabana Larga - Esc. Efrain R. Murillo'],
['municipio_id' => 12, 'nombre' =>  'Salalica - Esc. Nuev'],

['municipio_id' => 13, 'nombre' =>  'Aragua - Esc. Jose M. Gonzales'],
['municipio_id' => 13, 'nombre' =>  'Cofradia - Esc. Republica de Honduras'],
['municipio_id' => 13, 'nombre' =>  'El Aguacatal - Ceb Rafael Martinez'],
['municipio_id' => 13, 'nombre' =>  'El Circulo - Esc. Rafael Pineda Ponce'],
['municipio_id' => 13, 'nombre' =>  'El Guayabal - Esc. Maestra Pura'],
['municipio_id' => 13, 'nombre' =>  'El Llano de San Juan Garcia - Esc. Juan Ramon Molina'],
['municipio_id' => 13, 'nombre' =>  'El Plomo - Esc. Filiberto Gonzales'],
['municipio_id' => 13, 'nombre' =>  'Guasucaran - Esc. Lempira'],
['municipio_id' => 13, 'nombre' =>  'Guerisne - Esc. Tierra de Promision'],
['municipio_id' => 13, 'nombre' =>  'La Cofradia - Esc. Ruben Dario'],
['municipio_id' => 13, 'nombre' =>  'Las Cienegas - Esc. Jose Trinidad Reyes'],
['municipio_id' => 13, 'nombre' =>  'Ojojona - Esc. Pablo Zelaya'],
['municipio_id' => 13, 'nombre' =>  'San Sebastian - Esc. Rural Mixta Francisco Morazan'],
['municipio_id' => 13, 'nombre' =>  'Surcos de Caña - Esc. John F. Kennedy'],
['municipio_id' => 13, 'nombre' =>  'Suyatillo - Esc. J'],

['municipio_id' => 14, 'nombre' =>  'El Encino - Esc. 22 de Mayo'],
['municipio_id' => 14, 'nombre' =>  'El Matapalo - Esc. Dionisio de Herrera'],
['municipio_id' => 14, 'nombre' =>  'El Nance - Esc. 11 de Noviembre'],
['municipio_id' => 14, 'nombre' =>  'El Naranjo - Ceb Francisco Mejia'],
['municipio_id' => 14, 'nombre' =>  'El Tablon - Esc. Mariano P. Guevara'],
['municipio_id' => 14, 'nombre' =>  'Guatemalita - Ceb Francisco Morazan'],
['municipio_id' => 14, 'nombre' =>  'La Joya Del Quebracho - Ceb Jose Trinidad Cabañas'],
['municipio_id' => 14, 'nombre' =>  'Orica - Ceb 15 de Septiembre'],
['municipio_id' => 14, 'nombre' =>  'Piedras Gordas - Esc. Alvaro Contreras'],
['municipio_id' => 14, 'nombre' =>  'Rio Arriba - Esc. Estados Unidos'],
['municipio_id' => 14, 'nombre' =>  'San Cristobal O El Ocotal - Esc. Cristobal Colon'],
['municipio_id' => 14, 'nombre' =>  'San Francisco de Orica - Ceb Jose Cecilio Del Valle'],
['municipio_id' => 14, 'nombre' =>  'San Juan O Montaña de la Flor - Esc. Ruben Martinez Rodas'],
['municipio_id' => 14, 'nombre' =>  'San Marquitos - '],

['municipio_id' => 15, 'nombre' =>  'Agua Caliente - Esc. Dionisio de Herrera'],
['municipio_id' => 15, 'nombre' =>  'Azacualpita - Esc. Miguel Paz Barahora'],
['municipio_id' => 15, 'nombre' =>  'El Jicaral No. 1 - Esc. Manuel Bonilla'],
['municipio_id' => 15, 'nombre' =>  'El Llano - Esc. Dionisio de Herrera'],
['municipio_id' => 15, 'nombre' =>  'El Rebalse - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 15, 'nombre' =>  'El Rodeo - Esc. 15 de Septiembre'],
['municipio_id' => 15, 'nombre' =>  'El Verdugo - Esc. Republica de Honduras'],
['municipio_id' => 15, 'nombre' =>  'Guajiniquil - Esc. La Libertad'],
['municipio_id' => 15, 'nombre' =>  'Hermita San Carlos - Esc. Juan Lindo'],
['municipio_id' => 15, 'nombre' =>  'La Ermita - Esc. Miguel Paz Barahona'],
['municipio_id' => 15, 'nombre' =>  'La Guadalupe - Esc. Cristobal Colon'],
['municipio_id' => 15, 'nombre' =>  'Laguna Seca - Esc. Carlos Roberto Reina'],
['municipio_id' => 15, 'nombre' =>  'Reitoca - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 15, 'nombre' =>  'Sabanetas - Esc. Ramon Rosa'],
['municipio_id' => 15, 'nombre' =>  'Samalare - Esc. Lempira'],
['municipio_id' => 15, 'nombre' =>  'San Bartolo - Esc. Francisco Morazan'],
['municipio_id' => 15, 'nombre' =>  'Saracaran - Esc.'],

['municipio_id' => 16, 'nombre' =>  'Apasinigua - Ceb Pablo Portillo Figueroa'],
['municipio_id' => 16, 'nombre' =>  'Apatana - Esc Rural Mixta Juan Lindo'],
['municipio_id' => 16, 'nombre' =>  'Arenales - Esc. Presentacion Centeno'],
['municipio_id' => 16, 'nombre' =>  'Cofradia - Esc. Rural Mixta 21 de Febrero'],
['municipio_id' => 16, 'nombre' =>  'El Calvario No. 2 - Esc. Lempira'],
['municipio_id' => 16, 'nombre' =>  'El Divisadero - Esc. Jose Trinidad Reyes'],
['municipio_id' => 16, 'nombre' =>  'El Llano - Ceb Cristobal Colón'],
['municipio_id' => 16, 'nombre' =>  'El Obrajito - Esc. Ruben Dario'],
['municipio_id' => 16, 'nombre' =>  'El Ocotal Viejo - Esc. Francisco de Miranda'],
['municipio_id' => 16, 'nombre' =>  'El Rincon - Ceb. El Rincón'],
['municipio_id' => 16, 'nombre' =>  'El Rio - Ceb Dionisio de Herrera'],
['municipio_id' => 16, 'nombre' =>  'El Tule - Esc. Miguel Paz Barahona'],
['municipio_id' => 16, 'nombre' =>  'El Vino - Esc. Jose Trinidad Reyes'],
['municipio_id' => 16, 'nombre' =>  'La Cañada - Ceb Alvaro Contreras'],
['municipio_id' => 16, 'nombre' =>  'La Ceiba - Ceb José Cecilio Del Valle'],
['municipio_id' => 16, 'nombre' =>  'La Trinidad - Ceb 11 de Noviembre'],
['municipio_id' => 16, 'nombre' =>  'Los Carbones - Esc. Santa Lucia'],
['municipio_id' => 16, 'nombre' =>  'Los Chorros - Ceb Gloria Figueroa de López'],
['municipio_id' => 16, 'nombre' =>  'Los Infiernitos - Esc. Vicente Mejia Colindres'],
['municipio_id' => 16, 'nombre' =>  'Los Nanzales - Esc. Francisco Morazan'],
['municipio_id' => 16, 'nombre' =>  'Los Portillos - Ceb Marco Aurelio Soto'],
['municipio_id' => 16, 'nombre' =>  'Monte Grande - Esc. Francisco Morazan'],
['municipio_id' => 16, 'nombre' =>  'Plan de San Antonio - Esc. Plan de San Antonio'],
['municipio_id' => 16, 'nombre' =>  'Plan Del Oregano - Esc. Lempira'],
['municipio_id' => 16, 'nombre' =>  'Sabana de Encima - Esc. Sabana de Encima'],
['municipio_id' => 16, 'nombre' =>  'Sabanagrande - Ceb Francisco Morazán'],
['municipio_id' => 16, 'nombre' =>  'San Nicolas O El Zapote - Ceb Juan Angel Banegas'],
['municipio_id' => 16, 'nombre' =>  'Santa Barbara - Ceb Moisés Aguilar'],
['municipio_id' => 16, 'nombre' =>  'Yure - Ceb 14 de'],

['municipio_id' => 17, 'nombre' =>  'El Chaguite - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 17, 'nombre' =>  'El Jicarito - Esc. Francisco Morazan'],
['municipio_id' => 17, 'nombre' =>  'El Llano Del Ocotal - Esc. Mixta Marco Antonio Andino'],
['municipio_id' => 17, 'nombre' =>  'El Suyatillo - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 17, 'nombre' =>  'El Zamoranito - Esc. Carlos Roberto Reina'],
['municipio_id' => 17, 'nombre' =>  'Joya Grande - Ceb Miguel Paz Barahona'],
['municipio_id' => 17, 'nombre' =>  'La Cienega - Ceb Jose Cecilio de Valle'],
['municipio_id' => 17, 'nombre' =>  'La Estancia - Esc. Jose Cecilio Del Valle'],
['municipio_id' => 17, 'nombre' =>  'Las Mesas - Esc. Augusto C. Coello'],
['municipio_id' => 17, 'nombre' =>  'San Antonio de Oriente - Esc. Esteban Guardiola'],
['municipio_id' => 17, 'nombre' =>  'San Francisco - Esc. Roberto Hasbum'],
['municipio_id' => 17, 'nombre' =>  'Santa Ines - Esc. Francisco Morazan'],
['municipio_id' => 17, 'nombre' =>  'Tabla Grande - Es'],

['municipio_id' => 18, 'nombre' =>  'El Hisopo - Esc. Valentin Aguilar'],
['municipio_id' => 18, 'nombre' =>  'El Horno - Esc. Marcos Carias Reyes'],
['municipio_id' => 18, 'nombre' =>  'El Sauce - Esc. Republica de Mexico'],
['municipio_id' => 18, 'nombre' =>  'El Terrero - Esc. Pedro Nufio'],
['municipio_id' => 18, 'nombre' =>  'La Crucita - Esc. Francisco Morazan'],
['municipio_id' => 18, 'nombre' =>  'San Buenaventura -'],

['municipio_id' => 19, 'nombre' =>  'El Escano de Tepale - Ceb Alvaro Contreras'],
['municipio_id' => 19, 'nombre' =>  'El Portillo de Siale - Esc. Francisco Morazan'],
['municipio_id' => 19, 'nombre' =>  'San Ignacio - Esc. Luis Landa'],
['municipio_id' => 19, 'nombre' =>  'San Jose Del Naranjal - Esc. Ramon Villeda Morales'],
['municipio_id' => 19, 'nombre' =>  'San Miguel de Barrosa - Ceb Francisco Morazan'],
['municipio_id' => 19, 'nombre' =>  'Urrutia - Ceb Regina E. Molina'],
['municipio_id' => 19, 'nombre' =>  'Yoculateca - Ceb Ma'],

['municipio_id' => 20, 'nombre' =>  'Agua Fria - Esc. Francisco Morazan'],
['municipio_id' => 20, 'nombre' =>  'Cerro Bonito - Esc. Lempira'],
['municipio_id' => 20, 'nombre' =>  'Chandala - Esc. Alvaro Contreras'],
['municipio_id' => 20, 'nombre' =>  'Cofradia - Esc. Besser Arguijo'],
['municipio_id' => 20, 'nombre' =>  'El Carbon - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 20, 'nombre' =>  'El Zarzal - Esc. Alvaro Contreras'],
['municipio_id' => 20, 'nombre' =>  'El Zurzular - Esc. Francisco Morazan'],
['municipio_id' => 20, 'nombre' =>  'Joyas de Carballo - Esc. Jose Rivera Paz'],
['municipio_id' => 20, 'nombre' =>  'La Cruz O Suyapa - Esc. Japon'],
['municipio_id' => 20, 'nombre' =>  'Las Delicias - Esc. Rafael Bardales Bueso'],
['municipio_id' => 20, 'nombre' =>  'Pacayas - Esc. Lempira'],
['municipio_id' => 20, 'nombre' =>  'Pajarillos - Esc. Martin Alvarado'],
['municipio_id' => 20, 'nombre' =>  'San Jose de Ramos - Esc. Hector Tranquilino Ucles'],
['municipio_id' => 20, 'nombre' =>  'San Juan de Flores - Esc. Francisco Ferrera'],
['municipio_id' => 20, 'nombre' =>  'Tomatin - Esc. Ing. Francisco Gaitan'],
['municipio_id' => 20, 'nombre' =>  'Yamaguare - Esc. '],

['municipio_id' => 21, 'nombre' =>  'El Guanacaste - Esc. Ramon Rosa'],
['municipio_id' => 21, 'nombre' =>  'Mala Laja - Esc. Filomena Maldonado'],
['municipio_id' => 21, 'nombre' =>  'Piedra Parada - Esc. Terencio Sierra'],
['municipio_id' => 21, 'nombre' =>  'Quebrada Arriba - Esc. Rafael Pineda Ponce'],
['municipio_id' => 21, 'nombre' =>  'San Miguelito - Esc. Gabriel Ochoa'],
['municipio_id' => 21, 'nombre' =>  'Santa Martha - Esc.'],

['municipio_id' => 22, 'nombre' =>  'Babanato - Inst. Santa Ana'],
['municipio_id' => 22, 'nombre' =>  'El Cruce - Esc. Primero de Agosto'],
['municipio_id' => 22, 'nombre' =>  'El Sauce - Esc. Republica de Mexico'],
['municipio_id' => 22, 'nombre' =>  'La Bodega - Ceb 18 de Noviembre'],
['municipio_id' => 22, 'nombre' =>  'La Cali - Esc. Lempira'],
['municipio_id' => 22, 'nombre' =>  'Las Cuevecitas - Esc. Alfonso Guillen Zelaya'],
['municipio_id' => 22, 'nombre' =>  'Las Mesitas - Esc. Republica de Canada'],
['municipio_id' => 22, 'nombre' =>  'Los Encinos - Esc. Miguel Paz Barahona'],
['municipio_id' => 22, 'nombre' =>  'Nueva Arcadia - Esc. El Futuro'],
['municipio_id' => 22, 'nombre' =>  'Santa Ana - Esc. Juan Lindo'],
['municipio_id' => 22, 'nombre' =>  'Sicatacare - Esc. Francisco Morazan'],
['municipio_id' => 22, 'nombre' =>  'Tierra Del Padre - '],

['municipio_id' => 23, 'nombre' =>  'El Chimbo - Esc. Dionisio de Herrera'],
['municipio_id' => 23, 'nombre' =>  'El Eden - Esc. Marco Aurelio Soto'],
['municipio_id' => 23, 'nombre' =>  'La Pancha - Esc. Martha Nazar'],
['municipio_id' => 23, 'nombre' =>  'Loma Alta Del Sur - Esc. Nuevos Horizontes'],
['municipio_id' => 23, 'nombre' =>  'Loma Alta Norte - Esc. Rural Mixta Union Centro Americana'],
['municipio_id' => 23, 'nombre' =>  'Santa Lucia - Inst. Santa Lucía'],
['municipio_id' => 23, 'nombre' =>  'Zarabanda - Esc. Ju'],

['municipio_id' => 24, 'nombre' =>  'Agua Blanca - Esc. Vicente Caceres'],
['municipio_id' => 24, 'nombre' =>  'Bo. El Centro - Ceb República Del Ecuador'],
['municipio_id' => 24, 'nombre' =>  'Bo. La Ceiba - Esc. Roberto Suazo Cordova'],
['municipio_id' => 24, 'nombre' =>  'Bo. La Victoria - Inst. Manuel Zelaya Rosales'],
['municipio_id' => 24, 'nombre' =>  'Candelaria - Esc. Gloria Figueroa de Lopez'],
['municipio_id' => 24, 'nombre' =>  'Casillas - Esc. Republica de Honduras'],
['municipio_id' => 24, 'nombre' =>  'Col. Carias y Rodriguez - Ceb José Arturo Duarte'],
['municipio_id' => 24, 'nombre' =>  'Corralitos - Ceb. Augusto C. Coello'],
['municipio_id' => 24, 'nombre' =>  'El Estero - Esc. Dr. Eugenio Matute Canizales'],
['municipio_id' => 24, 'nombre' =>  'El Ocotal - Esc. Soberania Nacional'],
['municipio_id' => 24, 'nombre' =>  'El Rosario - Esc. John F. Kennedy'],
['municipio_id' => 24, 'nombre' =>  'Jalaca - Esc. Francisco Morazan'],
['municipio_id' => 24, 'nombre' =>  'La Cuesta O la Primer Sabana - Esc. Jesus Soto'],
['municipio_id' => 24, 'nombre' =>  'La Ermita - Esc. Juan Lindo No. 1 y No. 2'],
['municipio_id' => 24, 'nombre' =>  'La Esperanza - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 24, 'nombre' =>  'La Horqueta - Esc. Centro America'],
['municipio_id' => 24, 'nombre' =>  'La Labranza - Esc. Luis Landa'],
['municipio_id' => 24, 'nombre' =>  'La Majada Verde - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 24, 'nombre' =>  'Las Quebradas - Esc. John F. Kennedy'],
['municipio_id' => 24, 'nombre' =>  'Los Charcos - Ceb Luis Landa'],
['municipio_id' => 24, 'nombre' =>  'Los Izotes - Esc. Ernesto Amado Pinot'],
['municipio_id' => 24, 'nombre' =>  'Palmira - Esc. Republica de Honduras'],
['municipio_id' => 24, 'nombre' =>  'Rio Dulce - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 24, 'nombre' =>  'San Antonio de Pastos - Esc. San Antonio de Pastos'],
['municipio_id' => 24, 'nombre' =>  'Terrero Colorado - Esc. Lempira'],
['municipio_id' => 24, 'nombre' =>  'Valle Arriba - Esc. Jose Trinidad Reyes'],
['municipio_id' => 24, 'nombre' =>  'Zarzalosa - Esc. Fr'],

['municipio_id' => 25, 'nombre' =>  'Cofradia - Ceb Dionisio de Herrera'],
['municipio_id' => 25, 'nombre' =>  'Cuesta Grande - Esc. Sebastian Garcia'],
['municipio_id' => 25, 'nombre' =>  'El Plan de la Lima - Esc. Rural Mixta Francisco Morazan'],
['municipio_id' => 25, 'nombre' =>  'La Lima - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 25, 'nombre' =>  'Linaca - Esc. Jose Trinidad Reyes'],
['municipio_id' => 25, 'nombre' =>  'Macuelizo - Esc. Lempira'],
['municipio_id' => 25, 'nombre' =>  'Tatumbla - Esc. Rep'],

['municipio_id' => 26, 'nombre' =>  'Bo. El Canton - Esc. Rotaria Los Ángeles'],
['municipio_id' => 26, 'nombre' =>  'Bo. Sunteco - Inst. Tecnico Hector V. Medina'],
['municipio_id' => 26, 'nombre' =>  'Cerro Grande - Esc. Manuel Bonilla'],
['municipio_id' => 26, 'nombre' =>  'El Guanacaste - Esc. Juan Ramon Molina'],
['municipio_id' => 26, 'nombre' =>  'El Liquidambar - Esc. Vicente Chavez'],
['municipio_id' => 26, 'nombre' =>  'El Macuelizo - Esc. Evangelica Piedad'],
['municipio_id' => 26, 'nombre' =>  'El Retiro - Esc. Zea Arismendi'],
['municipio_id' => 26, 'nombre' =>  'El Sauce - Esc. Marco Aurelio Soto'],
['municipio_id' => 26, 'nombre' =>  'Esperanza - Esc. La Esperanza'],
['municipio_id' => 26, 'nombre' =>  'La Escondida - Esc. Barveris Pineda'],
['municipio_id' => 26, 'nombre' =>  'La Sabaneta - Esc. Francisco Morazan'],
['municipio_id' => 26, 'nombre' =>  'Las Cañadas - Ceb.israel Muñoz Franco'],
['municipio_id' => 26, 'nombre' =>  'Miravalle - Esc. Miravalle'],
['municipio_id' => 26, 'nombre' =>  'Valle de Angeles - Esc. Policarpo Bonilla'],

['municipio_id' => 27, 'nombre' =>  'Bo. El Centro - Esc. Miguel Paz Barahona'],
['municipio_id' => 27, 'nombre' =>  'El Coyolito - Esc. Trinidad Zavala'],
['municipio_id' => 27, 'nombre' =>  'El Pedregal - Esc. Federico Gonzales'],
['municipio_id' => 27, 'nombre' =>  'La Mesa - Esc. Alva'],

['municipio_id' => 28, 'nombre' =>  'El Aguacatal - Esc. Jose Trinidad Cabañas'],
['municipio_id' => 28, 'nombre' =>  'San Cristobal Del Infiernito - Esc. 19 de Junio'],
['municipio_id' => 28, 'nombre' =>  'San Jose de la Mora - Esc. Dionisio de Herrera'],
['municipio_id' => 28, 'nombre' =>  'Tierra Blanca - Inst. Independencia'],
['municipio_id' => 28, 'nombre' =>  'Trinidad de Quebradas - Ceb Manuel de Jesús Subirana'],
['municipio_id' => 28, 'nombre' =>  'Tuliapita - Esc. Pompilio Ortega'],
['municipio_id' => 28, 'nombre' =>  'Vallecillo - Esc. Fran'],




        ];

        DB::table('centro_votacions')->insert($centros);
    }
}
